baseURL = "https://benobi.one/"
languageCode = "en-us"
title = "benobi.one"
theme = ["hugo-embed-pdf-shortcode", "hugo-coder-portfolio"]
enableInlineShortcodes = true

DefaultContentLanguage = "en"
googleAnalytics = "G-13YHEX7C0B"

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

[pagination]
    pagerSize = 20

[markup.goldmark.renderer]
  unsafe = true

[services.disqus]
  shortname = "benobi"

[params]
    author = "Ben Sigman"
    description = "Bitcoin, Engineering, and Product Leadership"
    keywords = "bitcoin,engineering,product,leadership,developer,blockchain"
    info = "Bitcoin, Engineering, and Product Leadership"
    avatarurl = "images/bensigman.jpg"

    hideCredits = true
    hideCopyright = true

    # Bottom sns share
    snsShare = true
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = false
    enableFacebookShare = false
    enableHatenaShare = false
    enableLineShare = false
    enableLinkedInShare = false

    thumbnail = "images/benobi-one.png"

    # Custom CSS
    custom_css = ["css/custom.css"]

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/bensig/"
[[params.social]]
    name = "X"
    icon = "fab fa-x-twitter"
    weight = 2
    url = "https://x.com/bensig/"

[languages]
    [languages.en]
        languagecode = "en"
        languagename = "English" # The language name to be displayed in the selector.
        title = "Benobi.one"

        # You can configure the theme parameter for each language.
        [languages.en.params]
            author = "Ben Sigman"
            info = "Systems engineer, author, and Bitcoin advocate"
            description = "Ben Sigman is a Bitcoin nerd who think a lot about security, and writes code and books when not evangelizing magic internet money."
            keywords = "bitcoin,engineering,product,leadership,developer,blockchain"

        [languages.en.menu] # It is possible to change the menu too.

            [[languages.en.menu.main]]
                name = "About"
                weight = 1
                url = "about"
            [[languages.en.menu.main]]
                name = "Blog"
                weight = 2
                url = "posts"
            [[languages.en.menu.main]]
                name = "Projects"
                weight = 3
                url = "projects"
            [[languages.en.menu.main]]
                name = "Advocacy"
                weight = 4
                url = "initiatives"
            [[languages.en.menu.main]]
                name = "Resources"
                weight = 5
                url = "resources"
            [[languages.en.menu.main]]
                name = "Workshop"
                weight = 6
                url = "pocketcoding"
            [[languages.en.menu.main]]
                name = "Contact"
                weight = 7
                url = "contact"
